#!/bin/sh

### BEGIN INIT INFO
# Provides:          custom-iptables
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      1 6 0
# Short-Description: iptables rules saver and loader
# Description:       custom-iptables is a program that permits the restoration
#                    of custom and default iptables configuration files, as
#                    as well as saving the custom configuration.
### END INIT INFO

NAME=`basename $0`
PID_FILE="/var/run/$NAME.pid"
CONFDIR="/etc/custom-iptables"
CUSTOMCONF="$CONFDIR/iptables.conf"
DEFAULTCONF="$CONFDIR/iptables.default.conf"

is_running(){
	[ -f $PID_FILE ]
}

checkconfdir(){
	if [ ! -d $CONFDIR ]; then
		mkdir $CONFDIR
	fi
}

defaultconf(){
	cat << EOF
*filter
:INPUT ACCEPT
:FORWARD ACCEPT
:OUTPUT ACCEPT
COMMIT
*nat
:PREROUTING ACCEPT
:INPUT ACCEPT
:OUTPUT ACCEPT
:POSTROUTING ACCEPT
COMMIT
EOF
}

case "$1" in
	start)
		if is_running; then
			echo "Already loaded."
		else
			echo -n "Loading custom configuration..."
			checkconfdir

			if [ -f $CUSTOMCONF ]; then
				iptables-restore < $CUSTOMCONF
				echo "Loaded"
				echo $! > $PID_FILE
			else
				echo "There is no custom configuration."
				exit 1
			fi
		fi
		;;
	stop)
		if is_running; then
			echo -n "Restoring default rules..."
			checkconfdir

			if [ ! -f $DEFAULTCONF ]; then
				defaultconf > $DEFAULTCONF
			fi

			iptables-restore < $DEFAULTCONF
			echo "Restored."

			if [ -f "$PID_FILE" ]; then
				rm "$PID_FILE"
			fi
		else
			echo "Not running"
		fi
		;;
	restart)
		$0 stop
		$0 start
		;;
	status)
		if is_running; then
			echo "Running"
		else
			echo "Stopped"
			exit 1
		fi
		;;
	save)
		checkconfdir
		iptables-save > $CUSTOMCONF
		echo "Saved custom configuration."
		;;
	*)
		echo "Usage: /etc/init.d/custom-iptables {start|stop|restart|status|save}"
		exit 1
		;;
esac

exit 0
